### ISSUE TITLE
Please use "unquote_plus" to decode the parameter of code.

### ISSUE THREAD

**Issue by FATESAIKOU** [KeepLearningFromSideProject/scheduler#1]
Regarding to the usage of http protocol for our purpose, some invalid characters(towards the original http protocol) could be contained in a crawling request.

So, to deal with this issue, it is better for us to use these below instead.
* [quote_plus](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote_plus): for encode
* [unquote_plus](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.unquote_plus): for decode

sincerely yours,
FATESAIKOU

**Comment by chungyichi** [comment]
I added quote_plus & unquote_plus when pass parameter into subprocess.
