### ISSUE TITLE
Need some patch to make the return value more elegant and concise

### ISSUE THREAD

**Issue by FATESAIKOU** [KeepLearningFromSideProject/scheduler#2]
As the title suggests, to make the return value more elegant and concise, please give [this place](https://github.com/KeepLearningFromSideProject/scheduler/blob/master/worker/ezworker.py#L15) a change.

from
> print(out)

to
> print(out.decode("utf-8"), end='')

sincerely yours,
FATESAIKOU

**Comment by chungyichi** [comment]
Fixed
