### ISSUE TITLE
Please provide another way for altering the code more easily

### ISSUE THREAD

**Issue by FATESAIKOU** [KeepLearningFromSideProject/scheduler#3]
As the title suggests, it may be a good way for a dockerfile using git-clone to build the initial environment.
But for my experience, on the contrary, it is always important for users can debug/change with your program very easily.

So, is it possible for you to alter [this command](https://github.com/KeepLearningFromSideProject/scheduler/blob/master/Dockerfile#L4) from getting source from github to getting it from the local storage instead?
Or you can just provide another dockerfile just for this issue.

sincerely yours,
FATESAIKOU

**Comment by chungyichi** [comment]
In this version, I actually didn't take care of it is convenient for debugging or not.

I would provide another Dockerfile to use "bind mount", that allow docker process or non-docker process to edit files, and then you should set the project directory path manually.

**Comment by FATESAIKOU** [comment]
I'm not really recommend the way you chosen for people to debug.
The reason is: "There is still no way for user to alter any lines of the code(or config) before they run the image".

Because of the reason above, people will be required to alter the code(or config) every time they run this image firstly, which is really annoying.
So, for this time, before you releasing it, the recommendation should be just build image based on the "local source", instead of github or any other source that user can't change.

**Comment by chungyichi** [comment]
I would try to add config in few days, and I am not really sure how it could be. 

All I did today is mount current directory to simplify the debug flow.
